version: '3.9'

services:
  postgres:
    image: postgres
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_DOCKER_PORT}'
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - comic_server:/var/lib/postgresql/data

  nestjs:
    image: registry.gitlab.com/comic_verse/cverse_server
    volumes:
      - ./coverage:/app/coverage
    ports:
      - '8000:8000'
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}:${POSTGRES_DOCKER_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
  
  redis:
    image: redis:7.2.1-alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    


volumes:
  comic_server:
